# Prepare the multiarch env
FROM alpine AS builder
RUN apk add curl && curl -L "https://github.com/balena-io/qemu/releases/download/v4.0.0%2Bbalena2/qemu-4.0.0.balena2-arm.tar.gz" | tar zxvf - -C . --strip-components 1

# Switch to the target image
FROM arm32v5/alpine

# Import qemu from the preparation
COPY --from=builder qemu-arm-static /usr/bin

# The app (always the same like in amd64)
WORKDIR /app
COPY runme.sh .
RUN chmod +x runme.sh
CMD ./runme.sh
